#!/usr/bin/env node

const { program } = require('commander');

const path = require('path');
const mergeDirs = require('./helpers/mergeDirs');
const execCommand = require('./helpers/execCommand');
const downloadDirectory = require('./helpers/downloadDirectory');
const tsx = require('tsx/cjs/api');
const fs = require('fs');

// ESM-only packages — lazy-loaded via dynamic import
const getInquirer = () => import('inquirer').then(m => m.default || m);
const getAxios = () => import('axios').then(m => m.default || m);

program
  .version(require('../package.json').version, '-v, --version');

function generateDbTypesFile(hiveSrc, frameworkDir, hiveProjectDir) {
  // Write to .hive/src/_generated/ (NOT $HIVE_SRC) to avoid triggering tsx watcher
  const generatedDir = path.resolve(hiveProjectDir, 'src', '_generated');

  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
  }

  // Scan for schema files in user resources and framework resources
  const schemas = [];
  const scanDirs = [
    { dir: path.resolve(hiveSrc, 'resources'), isUser: true },
    { dir: path.resolve(frameworkDir, 'src', 'resources'), isUser: false },
  ];

  for (const { dir: resourcesDir, isUser } of scanDirs) {
    if (!fs.existsSync(resourcesDir)) continue;

    for (const resourceName of fs.readdirSync(resourcesDir)) {
      const resourcePath = path.resolve(resourcesDir, resourceName);
      if (!fs.statSync(resourcePath).isDirectory()) continue;

      for (const file of fs.readdirSync(resourcePath)) {
        if ((file.endsWith('.schema.ts') || file.endsWith('.schema.js')) && !file.includes('extends.schema')) {
          const name = file.replace('.schema.ts', '').replace('.schema.js', '');
          // Skip if already found (user schemas override framework)
          if (!schemas.find(s => s.name === name)) {
            schemas.push({ name, resourceName, isUser });
          }
        }
      }
    }
  }

  // User schemas use @/ (hive/*), framework schemas use @hive/ (.hive/src/*)
  const imports = schemas.map(
    (s) => `import type ${s.name}Schema from '${s.isUser ? '@' : '@hive'}/resources/${s.resourceName}/${s.name}.schema';`
  );

  const entries = schemas.map(
    (s) => `  ${s.name}: MongoService<z.infer<typeof ${s.name}Schema>>;`
  );

  const content = `// Auto-generated by Hive — do not edit manually
import type { z } from 'zod';
import type MongoService from '@hive/lib/node-mongo/src/mongo-service';
${imports.join('\n')}

export interface DbServices {
${entries.join('\n')}
}
`;

  fs.writeFileSync(path.resolve(generatedDir, 'db.types.ts'), content);
  console.log('[hive] Generated db.types.ts');
}

program
  .command('init [projectName]')
  .description('Initialize a new Hive project')
  .option('--skip-install', 'Skip npm install')
  .option('--link', 'Use local file:.. dependency for @paralect/hive (for development)')
  .action(async (nameArg, options) => {
    try {
      let name = nameArg;

      if (!name) {
        const inquirer = await getInquirer();
        const answer = await inquirer.prompt([
          {
            type: 'input',
            name: 'projectName',
            message: 'Project name:',
            default: 'my-hive-app'
          }
        ]);
        name = answer.projectName;
      }

      const projectDir = path.resolve(process.cwd(), name);
      const projectName = path.basename(projectDir);
      const hiveVersion = require('../package.json').version;

      console.log(`\n🐝 Creating Hive project: ${projectName}\n`);

      const filesDir = path.resolve(__dirname, '../starter');
      await execCommand(`cp -r ${filesDir}/. ${projectDir}/`);

      // Rename .env.example to .env (stored as .example to avoid gitignore)
      const envExample = path.join(projectDir, 'apps', 'api', 'config', '.env.example');
      const envFile = path.join(projectDir, 'apps', 'api', 'config', '.env');
      if (fs.existsSync(envExample)) {
        fs.renameSync(envExample, envFile);
      }

      const templateFiles = ['package.json', 'apps/web/package.json'];
      const hiveRepoDir = path.resolve(__dirname, '..');
      const replacements = {
        '{{PROJECT_NAME}}': projectName,
        '{{HIVE_DEP}}': options.link ? `file:${path.relative(projectDir, hiveRepoDir)}` : `^${hiveVersion}`,
      };

      for (const file of templateFiles) {
        const filePath = path.join(projectDir, file);
        let content = fs.readFileSync(filePath, 'utf-8');
        for (const [key, value] of Object.entries(replacements)) {
          content = content.replaceAll(key, value);
        }
        fs.writeFileSync(filePath, content);
      }

      const projectPkgPath = path.join(projectDir, 'package.json');
      const projectPkg = JSON.parse(fs.readFileSync(projectPkgPath, 'utf-8'));
      fs.writeFileSync(projectPkgPath, JSON.stringify(projectPkg, null, 2));

      await execCommand(`cp -r ${path.resolve(__dirname, '..')}/framework/.cursor ${projectDir}/`);

      if (!options.skipInstall) {
        await execCommand(`npm install`, { cwd: projectDir });
      }

      console.log(`✅ Project created!\n`);
      console.log(`Next steps:\n`);
      console.log(`  cd ${path.relative(process.cwd(), projectDir)}`);
      console.log(`  npm run dev\n`);
      console.log(`Monorepo structure:`);
      console.log(`  apps/api  — Hive API server`);
      console.log(`  apps/web  — Next.js frontend\n`);
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });

program
  .command('run [dirPath]')
  .description('Run Hive server')
  .action(async (dirPath = '.') => {
    try {
      process.env.HIVE_SRC = path.resolve(process.cwd(), dirPath);

      const hiveProjectDir = path.resolve(process.cwd(), '.hive');
      await execCommand(`mkdir -p ${hiveProjectDir}`);
      await execCommand(`cp -r ${path.resolve(__dirname, '..')}/framework/ ${hiveProjectDir}`);

      // Generate types before starting the server
      generateDbTypesFile(process.env.HIVE_SRC, path.resolve(__dirname, '..', 'framework'), hiveProjectDir);

      tsx.require(`${hiveProjectDir}/src/app.ts`, __filename); // TSX doesn't work inside node_moduels
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });

program
  .command('prepare [dirPath]')
  .description('Prepare Hive server')
  .action(async (dirPath = '.') => {
    try {
      process.env.HIVE_SRC = path.resolve(process.cwd(), dirPath);
      const hiveProjectDir = path.resolve(process.cwd(), '.hive');

      await execCommand(`mkdir -p ${hiveProjectDir}`);
      await execCommand(`cp -r ${path.resolve(__dirname, '..')}/framework/. ${hiveProjectDir}`);
      await execCommand(`npm install --prefix ${hiveProjectDir}`);

      // Generate db.types.ts from discovered schemas
      generateDbTypesFile(process.env.HIVE_SRC, path.resolve(__dirname, '..', 'framework'), hiveProjectDir);
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });

program
  .command('deploy')
  .description('Build hive project')
  .action(async () => {
    try {
      let outDir = path.resolve(process.cwd(), './dist');
      await mergeDirs({ hiveSrc: path.resolve(process.cwd()), outDir });

      console.log('outDir', path.resolve(outDir, `./deploy/script`))
      await execCommand(`npm install --prefix ${path.resolve(outDir, `./deploy/script`)}`);

      await execCommand('node ./index.js', {
        cwd: path.resolve(outDir, `./deploy/script/src`)
      });
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });

program
  .command('install <plugin>')
  .description('Installs Hive plugin')
  .action(async (plugin) => {
    try {
      const destDir = process.cwd();

      await downloadDirectory(plugin);
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });


program
  .command('login')
  .description('Login into Hive Cloud')
  .action(async () => {
    const axios = await getAxios();
    const inquirer = await getInquirer();

    if (process.env.HIVE_TOKEN) {
      const user = (await axios({
        url: `https://hive-api-test.paralect.co/users/me`, method: 'get', headers: {
          'Authorization': `Bearer ${process.env.HIVE_TOKEN}`
        }
      })).data;

      console.log(`Already logged in!`, user);

      return;
    }

    const { email } = await inquirer.prompt([
      {
        type: 'input',
        name: 'email',
        message: 'Please enter your email:'
      }
    ]);

    try {
      await axios({ url: `https://hive-api-test.paralect.co/auth/login-code`, method: 'post', data: { email } });

      const { code } = await inquirer.prompt([
        {
          type: 'input',
          name: 'code',
          message: `One time code (sent to ${email})`,
        }
      ]);

      const { token, user } = (await axios({ url: `https://hive-api-test.paralect.co/auth/verify-login`, method: 'post', data: { email, code } })).data;

      console.log(`
        You're now logged into Hive! Welcome 🐝
        
        Important: to save access add HIVE_TOKEN to your env variables and your ~/.zshrc file

        export HIVE_TOKEN=${token}`)
    } catch (error) {
      console.error('An error occurred:', error.message);
    }
  });

program.parse(process.argv);