FROM node:16.13.1-alpine3.13 as base
RUN apk add --no-cache python3 py3-pip

ARG NODE_ENV=development
ARG APP_ENV
ARG PROJECT_SRC=/project

ENV NODE_ENV=$NODE_ENV
ENV APP_ENV=$APP_ENV
ENV PROJECT_SRC=$PROJECT_SRC

WORKDIR /app
COPY ["./package*.json", "/app/"]
# Disable husky
RUN npm set-script prepare ""

RUN npm ci --quiet
COPY . ./

RUN npm run build-assets

FROM base as migrator
CMD npm run migrate

FROM base as scheduler
CMD npm run schedule-dev

FROM base as api

EXPOSE 3001
EXPOSE 3012

CMD npm run dev 2>&1 | tee /logs/log.txt