import fs from 'fs';
import path from 'path';

interface SchemaEntry {
  name: string;
  resourceName: string;
  isHive: boolean;
}

const generateDbTypes = (schemas: SchemaEntry[]) => {
  // Write to the framework's own _generated dir (.hive/src/_generated/)
  // This is OUTSIDE $HIVE_SRC so tsx watch won't detect changes
  const generatedDir = path.resolve(__dirname, '..', '_generated');

  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
  }

  const imports = schemas.map((s) => {
    // User schemas use @/ (hive/*), framework schemas use @hive/ (.hive/src/*)
    const prefix = s.isHive ? '@' : '@hive';
    return `import type ${s.name}Schema from '${prefix}/resources/${s.resourceName}/${s.name}.schema';`;
  });

  const entries = schemas.map(
    (s) => `  ${s.name}: MongoService<z.infer<typeof ${s.name}Schema>>;`
  );

  const content = `// Auto-generated by Hive — do not edit manually
import type { z } from 'zod';
import type MongoService from '@hive/lib/node-mongo/src/mongo-service';
${imports.join('\n')}

export interface DbServices {
${entries.join('\n')}
}
`;

  const filePath = path.resolve(generatedDir, 'db.types.ts');
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';

  if (existing !== content) {
    fs.writeFileSync(filePath, content);
  }
};

export default generateDbTypes;
